# Generated by Django 4.0.5 on 2022-07-14 13:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0002_alter_register_table'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Register',
            new_name='EmailInfo',
        ),
    ]
